import { db } from "@/db"
import { plugins } from "@/db/schema"
import { inngest } from "@/inngest/client"
import { Octokit } from "octokit"

const octokit = new Octokit({
	auth: process.env.GITHUB_TOKEN,
})

const iconPaths = ["Resources/Icon128.png"]

const rawPluginData = [
	"https://github.com/CesiumGS/cesium-unreal",
	"https://github.com/arnaud-jamin/Cog",
	"https://github.com/ue4plugins/StreetMap",
	"https://github.com/ProjectBorealis/UEGitPlugin",
	"https://github.com/unrealcv/unrealcv",
	"https://github.com/TriAxis-Games/RealtimeMeshComponent",
	"https://github.com/nfrechette/acl-ue4-plugin",
	"https://github.com/pafuhana1213/KawaiiPhysics",
	"https://github.com/ArticySoftware/Articy3ImporterForUnreal",
	"https://github.com/mordentral/VRExpansionPlugin",
	"https://github.com/mordentral/AdvancedSessionsPlugin",
	"https://github.com/irajsb/UE4_Assimp",
	"https://github.com/TriAxis-Games/RealtimeMeshComponent",
	"https://github.com/Mountea-Framework/MounteaDialogueSystem",
	"https://github.com/HoussineMehnik/UE4-CustomGravityPlugin",
	"https://github.com/bw2012/UnrealSandboxTerrain",
	"https://github.com/PushkinStudio/PsRealVehicle",
	"https://github.com/mklabs/ue4-targetsystemplugin",
	"https://github.com/getnamo/WeaponTrace-Unreal",
	"https://github.com/modio/modio-ue",
	"https://github.com/ufna/VaRest",
	"https://github.com/getnamo/SocketIOClient-Unreal",
	"https://github.com/RyroNZ/UE4MasterServer",
	"https://github.com/CodeSpartan/UE4TcpSocketPlugin",
	"https://github.com/NinevaStudios/mqtt-utilities-unreal",
	"https://github.com/Tencent/sluaunreal",
	"https://github.com/rdeioris/LuaMachine",
	"https://github.com/jmgomez/NimForUE",
	"https://github.com/JanSeliv/LevelSequencerAudioTrimmer",
	"https://github.com/Noesis/UnrealPlugin",
	"https://github.com/JanSeliv/SettingsWidgetConstructor",
	"https://github.com/JanSeliv/CustomShapeButton",
	"https://github.com/getnamo/ZipUtility-Unreal",
	"https://github.com/EverNewJoy/VictoryPlugin",
	"https://github.com/coderespawn/prefabricator-ue4",
	"https://github.com/sinbad/StevesUEHelpers",
	"https://github.com/truong-bui/AsyncLoadingScreen",
	"https://github.com/getnamo/GlobalEventSystem-Unreal",
	"https://github.com/jorgenpt/Hermes",
	"https://github.com/cdpred/RedTalaria",
	"https://github.com/JanSeliv/PoolManager",
	"https://github.com/Incanta/unreal-bp-csv-parsing",
	"https://github.com/DoubleDeez/MDMetaDataEditor",
	"https://github.com/landelare/ue5coro",
	"https://github.com/strayTrain/SimpleEventSubsystemPlugin",
	"https://github.com/PushkinStudio/PsWebServer",
	"https://github.com/PushkinStudio/PsReplayKit",
	"https://github.com/PushkinStudio/PsFacebookMobile",
	"https://github.com/YetiTech-Studios/UE4GameLiftClientSDK",
	"https://github.com/BoredEngineer/MMT_Plugin",
	"https://github.com/Arisego/UnrealLive2D",
	"https://github.com/krumiaa/MindMaker",
	"https://github.com/ue4plugins/TextAsset",
	"https://github.com/ue4plugins/UEGeoCoordinates",
	"https://github.com/ue4plugins/ObjectBrowser",
	"https://github.com/ue4plugins/NdiMedia",
	"https://github.com/ue4plugins/BlackmagicMedia",
	"https://github.com/ue4plugins/LoadingScreen",
	"https://github.com/ue4plugins/VlcMedia",
	"https://github.com/ue4plugins/Linter",
	"https://github.com/JanSeliv/MorphsPlayer",
	"https://github.com/getnamo/myo-ue4",
	"https://github.com/getsetgames/Swipe",
	"https://github.com/KhArtNJava/MySQLConnectorUE4Plugin",
	"https://github.com/darkwere/ServerRecast",
	"https://github.com/JanSeliv/FunctionPicker",
	"https://github.com/SourySK/NiagaraUIRenderer",
	"https://github.com/google/play-unreal-engine-plugin",
	"https://github.com/VoxelPlugin/VoxelPluginFreeLegacy",
	"https://github.com/alexismorin/Greebler",
	"https://github.com/midgen/cashgenUE",
	"https://github.com/orfeasel/DungeonGenerator",
	"https://github.com/BenPyton/ProceduralDungeon",
	"https://github.com/ufna/VaFogOfWar",
	"https://github.com/PushkinStudio/PsRealVehicle",
	"https://github.com/mklabs/ue4-targetsystemplugin",
	"https://github.com/NoahZuo/GhostMeshPlugin",
	"https://github.com/kwonoh/OpenCL.uplugin",
	"https://github.com/gtreshchev/RuntimeFilesDownloader",
	"https://github.com/gtreshchev/RuntimeAudioImporter",
	"https://github.com/RaiaN/RuntimeImageLoader",
	"https://github.com/Chrizey91/RuntimeMeshLoader",
	"https://github.com/getnamo/TensorFlow-Unreal",
	"https://github.com/Allysony/tensorflow2-ue4-ar",
	"https://github.com/mika314/UELlama",
	"https://github.com/gameDNAstudio/MobileUtils",
	"https://github.com/ufna/VaRest",
	"https://github.com/vizor-games/InfraworldRuntime",
	"https://github.com/getnamo/UDP-Unreal",
	"https://github.com/getnamo/TCP-Unreal",
	"https://github.com/ayumax/ObjectDeliverer",
	"https://github.com/CodeSpartan/UE4TcpSocketPlugin",
	"https://github.com/How2Compute/Socketer",
	"https://github.com/kristjanvalur/UEWebsocket",
	"https://github.com/NinevaStudios/ble-utilities-unreal",
	"https://github.com/GDi4K/unreal-fetch",
	"https://github.com/charisma-ai/colyseus-unreal",
	"https://github.com/BwdYeti/GGPOUE4",
	"https://github.com/sha3sha3/UE-DSSPlugin",
	"https://github.com/sha3sha3/UE-EasyKafka",
	"https://github.com/FrozenStormInteractive/Unreal-SignalR",
	// "https://github.com/Dartanlla/OWS" // two plugins in one repo
	"https://github.com/locus84/LocusReplicationGraph",
	"https://github.com/pixeltris/USharp",
	"https://github.com/Tencent/UnLua",
	// "https://github.com/nxrighthere/UnrealCLR" // weird project layout
	"https://github.com/Tencent/puerts",
	"https://github.com/devcat-studio/SilvervineUE4Lua",
	"https://github.com/MaikKlein/unreal-rust",
	"https://github.com/hxhb/ue4-protobuf",
	"https://github.com/slowburn-dev/DataConfig",
	"https://github.com/gtreshchev/AudioAnalysisTools",
	"https://github.com/JanSeliv/LevelSequencerAudioTrimmer",
	"https://github.com/gtreshchev/RuntimeSpeechRecognizer",
	"https://github.com/OSVR/OSVR-Unreal",
	"https://github.com/Noesis/UnrealPlugin",
	"https://github.com/mitchemmc/VRUMGPlugin",
	"https://github.com/skeskinen/MeshWidgets",
	"https://github.com/gameDNAstudio/FastSwitcher",
	"https://github.com/EverNewJoy/UE4GamepadUMG",
	"https://github.com/ufna/VaTexAtlas",
	"https://github.com/ashea-code/BLUI",
	"https://github.com/segross/UnrealImGui",
	"https://github.com/benui-dev/UE-BUITween",
	"https://github.com/fairygui/FairyGUI-unreal",
	"https://github.com/DoubleDeez/MDFastBinding",
	"https://github.com/JanSeliv/SettingsWidgetConstructor",
	"https://github.com/RemRemRemRe/RemWidgetComponent",
	"https://github.com/sideeffects/HoudiniEngineForUnreal",
	"https://github.com/kitelightning/SuperluminalPlugin",
	"https://github.com/alexhajdu/WhatsMyPublicIP-ue4-plugin",
	"https://github.com/ayumax/WindowCapture2D",
	"https://github.com/midgen/UnrealFastNoise",
	"https://github.com/DoubleDeez/UnrealFastNoise2",
	"https://github.com/sinbad/StevesUEHelpers",
	"https://github.com/getnamo/GlobalEventSystem-Unreal",
	"https://github.com/zompi2/UE4EnhancedCodeFlow",
	"https://github.com/sha3sha3/UE-EasyJWT",
	"https://github.com/gtreshchev/RuntimeArchiver",
	"https://github.com/RemRemRemRe/RemRanges",
	"https://github.com/benui-dev/UE-BUITween",
	"https://github.com/kamrann/BTUtilityPlugin",
	"https://github.com/hxhb/ue4-export-nav-data",
	"https://github.com/mklabs/ue4-targetsystemplugin",
	"https://github.com/DescendentStudios/PingPlugin",
	"https://github.com/mrbandler/TwitchAuth",
	"https://github.com/SRombauts/UEGitPlugin",
	"https://github.com/SRombauts/UEPlasticPlugin",
	"https://github.com/EpicSkookumScript/SkookumScript-Plugin",
	"https://github.com/20tab/UnrealEnginePython",
	"https://github.com/ultraleap/UnrealPlugin",
	"https://github.com/hxhb/HotPatcher",
	"https://github.com/VoxelPlugin/VoxelPluginFreeLegacy",
	"https://github.com/proletariatgames/unreal.hx",
	"https://github.com/ue4plugins/VlcMedia",
	"https://github.com/sinbad/SPUD",
	"https://github.com/Voidware-Prohibited/ALSXT",
	"https://github.com/mik14a/VOX4U",
	"https://github.com/fairygui/FairyGUI-unreal",
	"https://github.com/Drakynfly/HeartGraph",
	"https://github.com/UnrealDirective/UDCore",
	"https://github.com/stkrwork/UE-Live2D",
	"https://github.com/mrmilomilo/FSMLite",
	"https://github.com/ProjectBorealis/RTXGI-UE-Plugin",
	"https://github.com/MothCocoon/FlowGraph",
	"https://github.com/Varcus-Solutions/VlcMedia-ue5-vlc4",
	"https://github.com/juddc/UE4RoadTools",
	"https://github.com/GamesBySarge/Unreal-NATS",
	"https://github.com/FreemanMakesGames/FMGInvSys",
	"https://github.com/Manoloon/AdvancedCameraSystem",
	"https://github.com/getnamo/UnrealJs",
	"https://github.com/ncsoft/Unreal.js-core",
	"https://github.com/alanedwardes/Estranged.Core",
	"https://github.com/Drakynfly/SquirrelUE",
	"https://github.com/Eragon-Brisingr/ImGui_WS",
	"https://github.com/benui-dev/UnrealImGui",
	"https://github.com/FaceFX/FaceFX-UE5",
	"https://github.com/FaceFX/FaceFX-UE4",
	"https://github.com/zurra/LXR-Free",
	"https://github.com/alanedwardes/Estranged.Core",
	"https://github.com/ZhengzhongSun/BPDiffer",
	"https://github.com/ShadowfallStudios/ALS-Community",
	"https://github.com/TensorWorks/UnrealGDAL",
	"https://github.com/channeldorg/channeld-ue-plugin",
	"https://github.com/nlebedenco/TPCE",
	"https://github.com/HoangGiang93/URoboViz",
	"https://github.com/ceeazy/SubstanceInUE4",
	"https://github.com/Evianaive/PMS",
	"https://github.com/getnamo/NodeJs-Unreal",
	"https://github.com/zr0n/Joyztick",
	"https://github.com/pixeltris/USharp",
	"https://github.com/code-iai/ROSIntegration",
	"https://github.com/NotYetGames/DlgSystem",
	"https://github.com/AleDel/Spout-UE4",
	"https://github.com/bw2012/UnrealSandboxTerrain",
	"https://github.com/SRombauts/UE4ProceduralMesh",
	"https://github.com/ValveSoftware/steamvr_unreal_plugin",
	"https://github.com/facebookarchive/UETorch",
	"https://github.com/rdeioris/glTFRuntime",
	"https://github.com/brifsttar/OpenDRIVE",
	"https://github.com/eidosmontreal/unreal-vdb",
	"https://github.com/VesCodes/ImGui",
	"https://github.com/calben/UnrealPakLoaderPlugin",
	"https://github.com/sideeffects/HoudiniEngineForUnreal-v2",
	"https://github.com/RVillani/UE4Duino",
	"https://github.com/xuhao1/Unreal-ROS-Plugin",
	"https://github.com/blueroseslol/BRPlugins",
	"https://github.com/sammyfreg/UnrealNetImgui",
	"https://github.com/benui-dev/UE-BUITween",
	"https://github.com/aws/amazon-gamelift-plugin-unreal",
	"https://github.com/kvoeten/UnrealBodyPlugin",
	"https://github.com/stereolabs/zed-UE5",
	"https://github.com/m2u/m2uUE4Plugin",
	"https://github.com/blueprintue/blueprintue-cpp-plugin",
	"https://github.com/dotBunny/CLionSourceCodeAccess",
	"https://github.com/Ikarus76/UEJoystickPlugin",
	"https://github.com/getnamo/hydra-ue4",
	"https://github.com/BenPyton/ProceduralDungeon",
	"https://github.com/splash-damage/future-extensions",
	"https://github.com/ar-tracking/UnrealDTrackPlugin",
	"https://github.com/thejinchao/turbolink",
	"https://github.com/nfrechette/acl-ue4-plugin",
	"https://github.com/getnamo/ZipUtility-Unreal",
	"https://github.com/bakjos/WebCameraFeed",
	"https://github.com/delebash/UnrealMapboxBridgePlugin",
	"https://github.com/lucoiso/UEAzSpeech",
	"https://github.com/getnamo/GlobalEventSystem-Unreal",
	"https://github.com/ArticySoftware/Articy3ImporterForUnreal",
	"https://github.com/bakjos/FFMPEGMedia",
	"https://github.com/mik14a/VOX4U",
	"https://github.com/GiM-GamesInMotion/gFurPro",
	"https://github.com/AccelByte/accelbyte-unreal-sdk-plugin",
	"https://github.com/Eragon-Brisingr/ToonShader",
	"https://github.com/PlayFab/PlayFabMultiplayerUnreal",
	"https://github.com/RPG3D/FileDownload-UE4",
	"https://github.com/kwonoh/OpenCL.uplugin",
	"https://github.com/gtreshchev/RuntimeAudioImporter",
	"https://github.com/benui-dev/UE-BUIValidator",
	"https://github.com/getnamo/myo-ue4",
	"https://github.com/teak421/SmoothZoom",
	"https://github.com/nachomonkey/RefreshAllNodes",
	"https://github.com/yujen/RN4UE4",
	"https://github.com/ydrive/EasySynth",
	"https://github.com/ash3D/UEVideoRecorder",
	"https://github.com/shanecolb/sphinx-ue4",
	"https://github.com/Flone-dnb/FWorldGenerator",
	"https://github.com/AppsFlyerSDK/appsflyer-unreal-plugin",
	"https://github.com/DarioMazzanti/OneEuroFilterUnreal",
	"https://github.com/cartzhang/Kinect4UE4Plugin",
	"https://github.com/mika314/UELlama",
	"https://github.com/cronos-labs/play-unreal-plugin",
	"https://github.com/millicast/millicast-player-unreal-engine-plugin",
	"https://github.com/davevill/UE4-Steamworks",
	"https://github.com/PushkinStudio/PsRealVehicle",
	"https://github.com/ScottRaffertyCG/MaterialVault",
	"https://github.com/electronicarts/IRIS-Unreal-Plugin",
	"https://github.com/J1blCblu/LockOnTarget",
	"https://github.com/getnamo/Llama-Unreal",
	"https://github.com/G7DAO/web3.unreal",
	"https://github.com/davevill/UE4-GameLift",
	"https://github.com/stomt/stomt-unreal-plugin",
	"https://github.com/UnrealSharp/UnrealSharp",
	"https://github.com/minimpoun/BlueprintWebsockets",
	"https://github.com/orig74/UE4PyServer",
	"https://github.com/ufna/VaQuoleUI",
	"https://github.com/gtreshchev/RuntimeFilesDownloader",
	"https://github.com/adamrehn/UE4Capture",
	"https://github.com/AutoSizeComments/AutoSizeComments",
	"https://github.com/NinevaStudios/yodo-mas-unreal",
	"https://github.com/tekifuta/IM4U",
	"https://github.com/android/adpf-unreal-plugin",
	"https://github.com/marshal-it/Protobuffer_UE4",
	"https://github.com/PushkinStudio/PsIronSource",
	"https://github.com/robcog-iai/USemLog",
	"https://github.com/ashe23/ProjectCleaner",
	"https://github.com/lucoiso/UEElementusInventory",
	"https://github.com/perfect-hand/ue5-cardgame",
	"https://github.com/mihe/tsu",
	"https://github.com/REWIND-co/Unreal-Engine-TeamCity-Plugin",
	"https://github.com/PipeRift/AttributesExtension",
	"https://github.com/cdpred/RedTalaria",
	"https://github.com/Nesquick0/TracyUnrealPlugin",
	"https://github.com/ankitkk/HTML5Networking",
	"https://github.com/cindustries/unreal-sqlite3",
	"https://github.com/colory-games/UEPlugin-AdvancedControlFlow",
	"https://github.com/GameTechDev/UnrealCapabilityDetect",
	"https://github.com/mrkriv/UnrealDotNet",
	"https://github.com/PushkinStudio/PsData",
	"https://github.com/mrkriv/QaDS",
	"https://github.com/jeirix/UnrealEngine5VLC",
	"https://github.com/NumbskullStudios/NumbskullSerialization",
	"https://github.com/rnixik/spider-navigation-plugin",
	"https://github.com/Ryan-DowlingSoka/RedTechArtTools",
	"https://github.com/NoahZuo/GhostMeshPlugin",
	"https://github.com/armory3d/armorpaint_unreal",
	"https://github.com/Deema35/LevelGen",
	"https://github.com/enlight/ue4-hg-plugin",
	"https://github.com/TheDiG3/TwitchPlay",
	"https://github.com/SteelSeries/gamesense-plugin-ue4",
	"https://github.com/Sartaq12/WaterInteractionPlugin",
	"https://github.com/h4lfheart/FortnitePortingServerUnreal",
	"https://github.com/seiko-dev/UI_Blooman",
	"https://github.com/JetBrains/RiderSourceCodeAccess",
	"https://github.com/aquanox/SubsystemBrowserPlugin",
	"https://github.com/maxenko/SodiumUE4",
	"https://github.com/gameDNAstudio/AndroidManifestConfigurator",
	"https://github.com/JsonAsAsset/JsonAsAsset",
	"https://github.com/armabon/UE4_CGAL",
	"https://github.com/xverse-engine/XV3DGS-UEPlugin",
	"https://github.com/ANtlord/LegsIKPlugin",
	"https://github.com/lucoiso/UEModularFeatures_ExtraActions",
	"https://github.com/PushkinStudio/PsWebServer",
	"https://github.com/edsonsantoro/NWheeledPlugin",
	"https://github.com/reznok/GMCAbilitySystem",
	"https://github.com/TheHugeManatee/OpenCV_Unreal",
	"https://github.com/enlight/Skelly",
	"https://github.com/DescendentStudios/BlinkenPlugin",
	"https://github.com/DescendentStudios/CommandLineParametersPlugin",
	"https://github.com/DescendentStudios/DSUtilityPlugin",
	"https://github.com/LouisRaverdy/DiscordRPC",
	"https://github.com/iwer/GeotiffLandscape",
	"https://github.com/HoussineMehnik/UE4-EditorScriptingToolsPlugin",
	"https://github.com/ElgSoft/ElgEditorScripting",
	"https://github.com/ScottKirvan/ScooterUtils",
	"https://github.com/rdeioris/AnselCapture",
	"https://github.com/getnamo/MachineLearningRemote-Unreal",
	"https://github.com/whoisEllie/FPSCore",
	"https://github.com/hxhb/GameFeaturePacker",
	"https://github.com/getsetgames/BlueprintReflection",
	"https://github.com/betidestudio/EOSIntegrationKit",
	"https://github.com/specklesystems/speckle-unreal",
	"https://github.com/rnixik/StereoPano",
	"https://github.com/zubEpty/UE5-Mediapipe-plugin",
	"https://github.com/AntiAnti/FreeAnimHelpers",
	"https://github.com/DoubleDeez/MDFastBinding",
	"https://github.com/DoubleDeez/MDViewModel",
	"https://github.com/noname0310/UE-MMD-Camera-Importer",
	"https://github.com/Conv-AI/Convai-UnrealEngine-SDK",
	"https://github.com/LazyTurtle/YetAnotherGraphPlugin",
	"https://github.com/OpenTimelineIO/OpenTimelineIO-Unreal-Plugin",
	"https://github.com/metabotics-ai/MetaLidar",
	"https://github.com/cormacmadden/Kinect-Body-Tracking-Unreal-Engine-Plugin",
	"https://github.com/AyoubKhammassi/UnrealMobileNeRF",
	"https://github.com/Ysgrathe/SQLiteGameDb",
	"https://github.com/AleDel/KinectXbox360-UE4",
	"https://github.com/kwstasg/WAC",
	"https://github.com/chaiyuntian/UE4Downloader",
	"https://github.com/HoangGiang93/URoboViz",
	"https://github.com/byteparrot/3DPresentationCreator",
	"https://github.com/StudioSyndiCatCaius/OmegaGameFramework",
	"https://github.com/ArmainAP/UnrealCam",
	"https://github.com/shadowmint/ue4-static-plugin",
	"https://github.com/JaydenMaalouf/JoystickPlugin",
	"https://github.com/ZackBradshaw/Bluepy",
	"https://github.com/DennisSoemers/HTN_Plan_Reuse",
	"https://github.com/linkinlin/FFmpegMedia",
	"https://github.com/EvilMindDevs/HMS-UnrealEngine-Plugin",
	"https://github.com/unraed/DialogueTree",
	"https://github.com/getsetgames/Chartboost",
	"https://github.com/technocranes/technocrane-unreal",
	"https://github.com/microsoft/Microsoft-OpenXR-Unreal",
	"https://github.com/betidestudio/SteamIntegrationKit",
	"https://github.com/smalllixin/PowerIK-UE5",
	"https://github.com/getnamo/TensorFlowNative-Unreal",
	"https://github.com/rezonated/openai-unreal",
	"https://github.com/wezrule/UE4NanoPlugin",
	"https://github.com/KennethBuijssen/MergeAssist",
	"https://github.com/WeAreROLI/JUCEUnrealBridge",
	"https://github.com/ashe23/GamedevHelper",
	"https://github.com/getnamo/CIMPlugin",
	"https://github.com/chaosgrid/ExtraCamWindow",
	"https://github.com/no5ix/flock-ai-ue4-plugin",
	"https://github.com/k2d222/TuioUnrealPlugin",
	"https://github.com/gameDNAstudio/MultiDex",
	"https://github.com/heyomidk/HardReferenceFinder",
	"https://github.com/opaquemultimedia/ProjectTangoPlugin",
	"https://github.com/flufy3d/UEWebSocket",
	"https://github.com/getsetgames/Sharing",
	"https://github.com/Kranox21/ChannelMachine",
	"https://github.com/gtreshchev/AudioAnalysisTools",
	"https://github.com/tahaHichri/UE-Bluetooth-Support",
	"https://github.com/Italink/GaussianSplattingForUnrealEngine",
	"https://github.com/recogni/ue4-orchestrator",
	"https://github.com/DarknessFX/DFoundryFX",
	"https://github.com/iwer/GeoReference",
	"https://github.com/puerts/EasyEditorPlugin",
	"https://github.com/iTwin/unreal-engine-3dft-plugin",
	"https://github.com/bennystarfighter/UnrealEngine-ObjectPool",
	"https://github.com/colory-games/UEPlugin-AccessVariableByName",
	"https://github.com/microsoft/UE4TelemetryVisualizer",
	"https://github.com/Volograms/volograms_unreal4_plugin",
	"https://github.com/splash-damage/automatron",
	"https://github.com/UnrealSharp/UnrealSharp-Cropout",
	"https://github.com/BenVlodgi/UE-ExtendedUnreal",
	"https://github.com/iwer/ShpGeometry",
	"https://github.com/max-verem/FreeDLiveLink",
	"https://github.com/etodanik/SvgBooga",
	"https://github.com/mattyman174/GenericItemization",
	"https://github.com/rfsheffer/QuestHands",
	"https://github.com/DiarIbrahim/PlacementSystem",
	"https://github.com/CrucibleNetworksLtd/EmergenceSDKUnreal",
	"https://github.com/carlosjtacon/unreal-lecorbusier-plugin",
	"https://github.com/TeamSpeak-Systems/teamspeak-sdk-unreal",
	"https://github.com/VSZue/DonAINavigation",
	"https://github.com/thirdweb-dev/unreal-engine",
	"https://github.com/Will747/UE-GeoViewer",
	"https://github.com/A57R4L/SceneViewExtensionTemplate",
	"https://github.com/UnrealDirective/UDCore",
	"https://github.com/Incanta/unreal-bp-csv-parsing",
	"https://github.com/amuTBKT/ImGuiPlugin",
	"https://github.com/1robertslattery/MenuPadPlus",
	"https://github.com/shun126/DungeonGenerator",
	"https://github.com/BugSplat-Git/bugsplat-unreal",
	"https://github.com/gameDNAstudio/AmazonServices",
	"https://github.com/hollsteinm/ReasonablePlanningAI",
	"https://github.com/ryanjon2040/AgoraViewportClient",
	"https://github.com/robcog-iai/libmongo",
	"https://github.com/Amirans/LyraGameCaptureTheFlag",
	"https://github.com/sasmaster/MP4Exporter",
	"https://github.com/MilkyEngineer/ViewportScriptingUtilities",
	"https://github.com/dantreble/Tweener",
	"https://github.com/suramaru517/AutoFootstep",
	"https://github.com/lucoiso/UEHttpGPT",
	"https://github.com/zompi2/UE4EnhancedCodeFlow",
	"https://github.com/DanialKama/UltimateUI",
	"https://github.com/gameDNAstudio/Crashlytics",
	"https://github.com/rdeioris/UnrealSTL",
	"https://github.com/zompi2/EditorCameraPositionUE4",
	"https://github.com/BrainGardenAI/TrackViz",
	"https://github.com/aceteam/Coroutines",
	"https://github.com/strayTrain/SimpleGameplayAbilitySystem",
	"https://github.com/ue4plugins/BlackmagicMedia",
	"https://github.com/electronicarts/texturesets",
	"https://github.com/Deams51/UE4-Gesture-Recognition-Plugin",
	"https://github.com/Nebukam/PCGExtendedToolkit",
	"https://github.com/4Players/odin-sdk-unreal",
	"https://github.com/Drakynfly/IdleDetector",
	"https://github.com/hannesdelbeke/unreal-plugin-python-script-editor",
	"https://github.com/SaxonRah/LindenmayerSystem",
	"https://github.com/zompi2/UE4EasyLocalizationTool",
	"https://github.com/Shiyatzu/OculusLipsyncPlugin-UE5",
	"https://github.com/nicholas477/EngineSimulatorPlugin",
	"https://github.com/Diddykonga/Spriter",
	"https://github.com/BraceYourselfGames/UE-BYGTextToSpeech",
	"https://github.com/Rectus/UE4SteamVRPassthrough",
	"https://github.com/1runeberg/RunebergVRPlugin",
	"https://github.com/miltoncandelero/CustomDetailsSectionsPlugin",
	"https://github.com/NinevaStudios/ble-utilities-unreal",
	"https://github.com/kartikeya-git/ProceduralLandscapeUE",
	"https://github.com/PopcornFX/UnrealEnginePopcornFXPlugin",
	"https://github.com/DescendentStudios/BlinkenPlugin",
	"https://github.com/BenVlodgi/UE-DynamicOctree",
	"https://github.com/BurgessYT/EasyV-for-Unreal",
	"https://github.com/ToniMacaroni/ModdingEx",
	"https://github.com/TheAshenWolf/WakaTimeForUE",
	"https://github.com/archangel4031/GASAssociate",
	"https://github.com/vagenv/BlockConstructor",
	"https://github.com/rlewicki/MeleeTrace",
	"https://github.com/rchaucha/UE-Portals",
	"https://github.com/ryanjon2040/AgoraStaticMeshThumbnailRenderer",
	"https://github.com/ntystudio/UnicodeBrowser",
	"https://github.com/StudioGobo/FillDDCForPIE",
	"https://github.com/Amirans/InteractionPlugin",
	"https://github.com/gerlogu/ProceduralFPSAnimationsPlugin",
	"https://github.com/BraceYourselfGames/UE-BYGCrossBranchLock",
	"https://github.com/Helium-Labs/UnrealSodium",
	"https://github.com/geordiemhall/WibblyWires",
	"https://github.com/TheEnbyWitch/ImGuiBlueprint",
	"https://github.com/Lukerrr/ue-cubemap-export",
	"https://github.com/antori82/FANTASIA",
	"https://github.com/munucrafts/CPP-UE-GetThumbnails",
	"https://github.com/gwaredd/MarkdownAsset",
	"https://github.com/gtreshchev/AndroidNative",
	"https://github.com/TheThirdFloor/UnrealP4Migrate",
	"https://github.com/jlnordin/LiveBlueprintVariableDebugging",
	"https://github.com/A57R4L/SceneViewExtTest",
	"https://github.com/MrDrElliot/Multi-Window-Plugin",
	"https://github.com/prajwalshettydev/UnrealGenAISupport",
	"https://github.com/strayTrain/SimpleEventSubsystemPlugin",
	"https://github.com/sinbad/SUDS",
	"https://github.com/outoftheboxplugins/QuickActions",
	"https://github.com/sirjofri/SlateStyleBrowser",
	"https://github.com/Adrien-Lucas/CustomShortcuts",
	"https://github.com/IDI-Systems/UnrealImGui",
	"https://github.com/Sharundaar/UIDatasource",
	"https://github.com/sleepCOW/CowNodes",
	"https://github.com/ArmainAP/Unreal-Engine-Widget-Spline-System",
]

const pluginData = [...new Set(rawPluginData)]

export const processPlugins = inngest.createFunction(
	{ id: "create-plugins" },
	{
		event: "plugins.create",
		// cron: 'every 1 hours',
	},
	async ({ event, step }) => {
		for (const url of pluginData) {
			await step.sleep("delay-10s", 10000)
			await step.run("queue-step", async () => {
				await inngest.send({
					name: "plugin.create",
					data: {
						url,
					},
				})
			})
		}
	},
)

export const processPlugin = inngest.createFunction(
	{ id: "create-plugin" },
	{
		event: "plugin.create",
	},
	async ({ event }) => {
		const url = event.data.url
		if (!url) return

		const repoName = url.split("/").slice(-2).join("/")
		const [owner, name] = repoName.split("/")
		const { data } = await octokit.rest.repos.get({
			owner,
			repo: name,
		})
		if (!data) {
			console.log("no repo found", owner, name)
			return
		}
		let readme = { content: "", path: "" }
		try {
			const { data: readmeData } = await octokit.rest.repos.getReadme({
				owner,
				repo: name,
				ref: data.default_branch,
			})
			readme = readmeData
		} catch (e) {
			console.log("no readme found", owner, name)
			return
		}

		const { data: treeData } = await octokit.rest.git.getTree({
			owner,
			repo: name,
			tree_sha: data.default_branch,
		})

		let uPluginFile = treeData.tree.find((file) => {
			return file.path.toLowerCase().endsWith(".uplugin")
		})

		if (!uPluginFile) {
			console.log("searching recursive", owner, data.name)

			// check full tree
			const { data: treeData } = await octokit.rest.git.getTree({
				owner,
				repo: name,
				tree_sha: data.default_branch,
				recursive: "true",
			})

			uPluginFile = treeData.tree.find((file) => {
				if (!file.path.toLowerCase().endsWith(".uplugin")) return false
				return file.path.split("/").length < 4
			})
			return
		}
		if (!uPluginFile) {
			console.log("no uplugin file found", owner, data.name)
			return
		}

		const { data: uePluginFile } = await octokit.rest.repos.getContent({
			owner,
			repo: name,
			path: uPluginFile.path,
		})

		if (!uePluginFile) {
			console.log("no uplugin file found", owner, data.name, uPluginFile.path)
			return
		}
		const uePluginFileContent = Array.isArray(uePluginFile) ? uePluginFile[0] : uePluginFile

		// @ts-ignore
		const uePluginContent = atob(uePluginFileContent.content)

		let uePluginContentJson: any
		try {
			uePluginContentJson = JSON.parse(JSON.stringify(uePluginContent))
		} catch (e) {
			console.log("error parsing uplugin file", owner, data.name, uPluginFile.path, e)
			return
		}

		const { data: uPluginIcon } = await octokit.rest.repos
			.getContent({
				owner,
				repo: name,
				path: iconPaths[0],
			})
			.catch(() => ({ data: undefined }))

		const values = {
			name: data.name,
			owner: data.owner.login,
			description: data.description,
			status: data.archived ? "archived" : "active",
			readme: atob(readme.content),
			readmePath: readme.path,
			// pluginRoot: ''
			githubId: data.id,
			githubLicense: data.license?.spdx_id,
			githubBranch: data.default_branch,
			githubStars: data.stargazers_count,
			githubForks: data.forks_count,
			githubPushedAt: new Date(data.pushed_at),
			githubWebsite: data.homepage,
			// githubStatus: data.archived ? "archived" : "active",
			// githubRepoIcon: data.owner.avatar_url,
			uePluginInfo: uePluginContentJson,
			// @ts-ignore
			uePluginIcon: uPluginIcon ? uPluginIcon.download_url : undefined,
			uePluginFilePath: uPluginFile.path,
			githubOwnerAvatar: data.owner.avatar_url,
			githubTopics: data.topics,
			categories: [],
			lastCheckedAt: new Date(),
			lastCheckedCommit: treeData.sha,
		}
		await db.insert(plugins).values(values).onConflictDoUpdate({
			target: plugins.githubId,
			set: values,
		})
	},
)
